blog/urls.py
from django.urls import path

from . views import ( ArticleListView,ArticleDetailView,
                      ArticleCategoryList,ArticleAuthorList,
                      ArticlePreView,SearchList

)

app_name = 'blog'


urlpatterns=[
    path('',ArticleListView.as_view(),name='home'),
    path('detail/<int:blog_id>/',ArticleDetailView.as_view(),name='detail'),
    path('category/<int:blog_id>/',ArticleCategoryList.as_view(),name='category'),
    path('preview/<int:pk>/',ArticlePreView.as_view(),name='preview'),
    path('search/',SearchList.as_view(),name='search'),
    path('search/page/<int:page>',SearchList.as_view(),name='search'),



]

config/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
# from django.conf import settings
# from django.conf.urls.static import static

from accounts.views import Login,Register,activate

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('about/',include('about.urls')),
    path('posts/',include('posts.urls')),
    path('contact/',include('contact.urls')),
    path('',include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls')),
    path("login/",Login.as_view(), name="login"),
    path("register/",Register.as_view(), name="register"),
    # re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',activate, name='activate'),
    path('activate/<uidb64>/<token>/',activate, name='activate'),
    path('comment/', include('comment.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),

]
# urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)

posts/urls.py
from django.urls import path

from . views import PostListView

app_name = 'posts'

urlpatterns = [
    path('',PostListView.as_view(),name='posts')
]

blog/models.py
from django.db import models
from django.utils import timezone
from accounts.models import User
from django.utils.html import format_html
from django.urls import reverse
from django.contrib.contenttypes.fields import GenericRelation

from accounts.models import User

from comment.models import Comment



class IPAddress(models.Model):
    ip_address = models.GenericIPAddressField()


#My Manager
class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status='P')

class CategoryManager(models.Manager):
    def active(self):
        return self.filter(status=True)



class Category(models.Model):
    parent = models.ForeignKey("self",related_name='childern',blank=True,null=True,on_delete=models.SET_NULL)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=100,unique=True)
    status = models.BooleanField(default=True)
    position = models.IntegerField()

    class Meta:
        ordering = ['parent__id','position']

    def __str__(self):
        return self.title

    objects = CategoryManager()


class Article (models.Model):
    STATUS_CHOICES=(
    ("D","Draft"),
    ("P","Published"),
    ("I","Investigation"),
    ("B","Back"),

    )
    author = models.ForeignKey(User,null=True,on_delete=models.SET_NULL,related_name='articles')
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=100,unique=True)
    descriptions = models.TextField()
    thumbnail = models.ImageField(upload_to='images')
    category = models.ManyToManyField(Category,related_name='articles')
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1,choices=STATUS_CHOICES)
    is_special = models.BooleanField(default=False)
    comments = GenericRelation(Comment)
    hits = models.ManyToManyField(IPAddress,through='ArticleHit' ,blank=True,related_name="hits")

    class Meta:
        ordering = ['-publish']

    def __str__(self):
        return self.title


    def thumbnail_tag(self):
        return format_html("<img width=100 height=70 style='border-radius:10px;' src='{}'>".format(self.thumbnail.url))

    def get_category(self):
        return ", ".join([category.title for category in self.category.active()])

    def get_absolute_url(self):
        return reverse('accounts:homee')

    objects = ArticleManager()


class ArticleHit(models.Model):
    article = models.ForeignKey(Article,on_delete=models.CASCADE)
    ip_address = models.ForeignKey(IPAddress,on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

blog/views.py
from django.views.generic import ListView,DetailView
from django.shortcuts import render,get_object_or_404
from django.core.paginator import Paginator
from django.db.models import Q


from . models import Article,Category

from accounts.models import User
from accounts.mixins import AuthorAccessMixin




class ArticleListView(ListView):
    queryset = Article.objects.filter(status="P")
    paginate_by = 4



class ArticleDetailView(DetailView):
    def get_object(self):
        blog_id = self.kwargs.get('blog_id')
        article =  get_object_or_404(Article,id=blog_id,status="P")

        ip_address = self.request.user.ip_address
        if ip_address not in article.hits.all():
            article.hits.add(ip_address)
        return article


class ArticleCategoryList(ListView):
    paginate_by = 4
    template_name = 'blog/category_list.html'
    
    def get_queryset(self):
        global category
        blog_id = self.kwargs.get('blog_id')
        category = get_object_or_404(Category.objects.active(),id=blog_id)
        return category.articles.published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = category
        return context


class ArticleAuthorList(ListView):
    paginate_by = 4
    template_name = 'blog/author_list.html'
    
    def get_queryset(self):
        global author
        username = self.kwargs.get('username')
        author = get_object_or_404(User,username=username)
        return author.articles.published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = author
        return context


class ArticlePreView(AuthorAccessMixin,DetailView):
    def get_object(self):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Article,pk=pk)


class SearchList(ListView):
    paginate_by = 4
    template_name = 'blog/search_list.html'
    
    def get_queryset(self):
        search = self.request.GET.get('q')
        return Article.objects.filter(Q(descriptions__icontains = search) | Q(title__icontains = search))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search'] = self.request.GET.get('q')
        return context
























# def home(request):
#     articles_list = Article.objects.filter(status="P")
#     paginator = Paginator(articles_list,4)
#     page = request.GET.get('page',1)
#     post = paginator.get_page(page)

#     context= {
#         'post':post,
#     }
#     return render(request,'blog/index.html',context)


# def detail(request,blog_id):
#     # detail =Article.objects.get(id=blog_id)
#     detail = get_object_or_404(Article,id=blog_id,status="P")
#     context={  
#         'detail':detail
#     }
#     return render(request,'blog/post.html',context)

# def category(request,blog_id,page=1):
#     # cat =Category.objects.get(id=blog_id)
#     cat = get_object_or_404(Category,id=blog_id,status=True)    
#     articles_list = cat.articles.published()
#     paginator = Paginator(articles_list,4)
#     page = request.GET.get('page',1)
#     post = paginator.get_page(page)

#     context={  
#         'cat':cat,
#         'post':post
#     }
#     return render(request,'blog/category.html',context)

posts/views.py
from django.shortcuts import render
from django.views.generic import ListView
from blog.models import Article



class PostListView(ListView):
    queryset = Article.objects.filter(status="P")
    paginate_by = 10
    template_name = 'posts/posts.html'
    context_object_name = 'posts'

templates/blog/article_detail.html
{% extends 'base.html' %}
{% load static %}
{% load comment_tags %} 
{% load ratings %}
{% load base_tags%}

{% block title %}Post{% endblock %}


{% block header%}
<header class="masthead" style="background-image:url('{{object.thumbnail.url}}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="post-heading">
                    <h1>{{object.title}}
                        {% if object.is_special %}
                        <span class="badge badge-danger" style="color: rgb(253, 253, 253);
                        font-size: 14px;">Special</span>
                    {% endif %}
                    </h1>
                    <h2 class="subheading">Iranian singer</h2>
                    <span class="meta">
                        Posted by
                        <a href="#!">Start Bootstrap</a>
                        on August 24, 2022
                    </span>
                    <div>
                        {% ratings object %} 
                    </div>
                    <div>Views: {{object.hits.count}}</div>
    
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block content %}
<!-- Post Content-->
        <article class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center" >
                    <div class="col-md-10 col-lg-8 col-xl-7 ">
                        
                        <h2 class="section-heading">{{object.title}}</h2>
                        {% if object.is_special %}
                            {% if user.is_authenticated and user.is_special_user or user == object.author or user.is_superuser %}
                                <p>{{object.descriptions|safe}}</p>
                            {% else %}
                            {{object.descriptions|striptags|truncatewords:50}}
                            <p class="alert alert-danger"> This Article Is Special Article <a class="alert-link" href="#">Special User</a> Buy Article</p>
                           
                            {% endif %}
                        {% else %}
                            <p>{{object.descriptions|safe}}</p>
                        {% endif %}

                        {% render_comments object request %}
                        {% include_bootstrap %}
                        <aside>
                        {% popular_articles %}
                        {% hot_articles %}
                        </aside>

                        
                           
                        
                        <blockquote class="blockquote">{{object.publish}}</blockquote>
                        <h2 class="section-heading">Picture</h2>
                        <a href="{{object.thumbnail.url}}"><img class="img-fluid" src="{{object.thumbnail.url}}" alt="..." /></a>
                        <span class="caption text-muted">To go places and do things that have never been done before – that’s what living is all about.</span>
                        <p>
                            &middot; {{object.title}}
                            <a href="http://Wikipedia.com/">Wikipedia</a>
                            <a href="https://www.ostadshajarian.com/">Weblog</a>
                        </p>
                    </div>
                </div>
            </div>
        </article>
     

{% endblock %}

templates/blog/article_list.html
{% extends 'base.html' %}
{% load static %}
{% load ratings %}
{% load base_tags %}
{% load humanize %}



{% block title %}Home{% endblock %}



{% block header%}

<header class="masthead" style="background-image: url('static/blog/assets/img/home.jpg')" >
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Music of Iran</h1>
                    <span class="subheading">Persian music</span>
                </div>  
            </div>
        </div>
    </div>
</header>

<!-- message alert  -->
{% if messages %}
<p class="alert alert-success">
    {% for message in messages %}
      {{ message }}
    {% endfor %}
</p>
{% endif %}
<!-- end message alert -->

{% endblock %}

{% block content %}

        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <!-- Post preview-->
                    {% for post in object_list %}
                    <div class="post-preview">
                        <a href="{% url 'blog:detail' post.id %}">
                            <h2 class="podfor st-title">
                                {{post.title}}
                                <div>
                                    {% ratings post %} 
                                </div>
                                <div>
                                    Views: {{post.hits.count}}
                                </div>
                                {% if post.is_special %}
                                    <span class="badge badge-danger" style="color: rgb(255, 255, 255);
                                    font-size: 14px;">Special</span>
                                {% endif %}
                            </h2>
                      
                           <img src="{{post.thumbnail.url}}" alt="" width="250" height="auto">
                            <h3 class="post-subtitle">{{post.descriptions|striptags|truncatewords:30}}</h3>
                        </a>
                        <p class="post-meta">
                            <a href="#">post created :
                                {{post.author.get_full_name}}</a>
                        </p>
                        <time>{{post.publish | naturaltime}}</time>
                        {% for cat in post.category.active %}
                        <a href="{% url 'blog:category' cat.id %}">#{{cat.title}}</a>
                    {% endfor %}
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
                   {% endfor %}

           <!-- Pager-->

                    {% if is_paginated %}

                    <nav aria-label="Page navigation example text-aline-center" >
                        <ul class="pagination">

                          {% if page_obj.has_previous %}
                            <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}">Previous</a></li>
                          {% endif%}

                          {% for post in page_obj.paginator.page_range %}

                            {% if post.number == page %}
                                <li class="page-item "><a class="page-link" href="?page={{post}}">{{post}}</a></li>
                            {% endif %}

                          {% endfor%}

                          {% if page_obj.has_next %}
                            <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">Next</a></li>
                          {% endif%}

                        </ul>
                    </nav>

                    {% endif %}
                    
                    <!-- <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a></div> -->
                    
                    <!-- End Pager-->

                </div>
            </div>
        </div>
{% endblock %}
      

templates/blog/author_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Author{% endblock %}


{% block header%}
<header class="masthead" style="background-image: url('static/blog/assets/img/post.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Author</h1>
                    <span class="subheading">A Blog </span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}


{% block content %}
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <h3 class="alert alert-primary text-center">Author {{author.get_full_name}}</h3>
                    <!-- Post preview-->
                    {% for post in object_list %}
                        <div class="post-preview">
                            <a href="{% url 'blog:detail' category.id %}">
                                <h2 class="podfor st-title">{{post.title}}</h2>
                            <img src="{{post.thumbnail.url}}" alt="">
                                <h3 class="post-subtitle">{{post.descriptions|truncatewords:30}}</h3>
                            </a>
                            <p class="post-meta">
                                Posted by
                                <a href="#!">{{post.status}}</a>
                                {{post.created}}
                            </p>
                            {% for cat in post.category.active %}
                            <a href="{% url 'blog:category' cat.id %}">#{{cat.title}}</a>
                            {% endfor %}
                        </div>
                        <!-- Divider-->
                        <hr class="my-4" />
                   {% endfor %}
                   <!-- Pager-->

                   {% if is_paginated %}

                   <nav aria-label="Page navigation example text-aline-center" >
                       <ul class="pagination">

                         {% if page_obj.has_previous %}
                           <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}">Previous</a></li>
                         {% endif%}

                         {% for post in page_obj.paginator.page_range %}

                           {% if post.number == page %}
                               <li class="page-item "><a class="page-link" href="?page={{post}}">{{post}}</a></li>
                           {% endif %}

                         {% endfor%}

                         {% if page_obj.has_next %}
                           <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">Next</a></li>
                         {% endif%}

                       </ul>
                   </nav>

                   {% endif %}




                   <!-- {% if post.has_other_pages%}

                   <nav aria-label="Page navigation example text-aline-center" >
                       <ul class="pagination">

                         {% if post.has_previous %}
                           <li class="page-item"><a class="page-link" href="?page={{post.previous_page_number}}">Previous</a></li>
                         {% endif%}

                         {% for post in post.paginator.page_range %}

                           {% if post.number == page %}
                               <li class="page-item "><a class="page-link" href="?page={{post}}">{{post}}</a></li>
                           {% endif %}

                         {% endfor%}

                         {% if post.has_next %}
                           <li class="page-item"><a class="page-link" href="?page={{post.next_page_number}}">Next</a></li>
                         {% endif%}

                       </ul>
                   </nav>

                   {% endif %}
                    -->
                   <!-- <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a></div> -->
                   
                   <!-- End Pager-->
                </div>
            </div>
        </div>
{% endblock %}
      

templates/blog/category_list.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Home{% endblock %}

{% block header%}
<header class="masthead" style="background-image: url('/static/blog/assets/img/cat.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>category</h1>
                    <span class="subheading">{{category.title}}</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block content %}
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <!-- Post preview-->
                    {% for post in object_list %}
                        <div class="post-preview">
                            <a href="{% url 'blog:detail' category.id %}">
                                <h2 class="podfor st-title">{{post.title}}</h2>
                            <img src="{{post.thumbnail.url}}" alt="">
                                <h3 class="post-subtitle">{{post.descriptions|truncatewords:30}}</h3>
                            </a>

                            <p class="post-meta">
                                Posted by
                                <a href="#!">{{post.status}}</a>
                                {{post.created}}
                            </p>
                            {% for cat in post.category.active %}
                            <a href="{% url 'blog:category' cat.id %}">#{{cat.title}}</a>
                            {% endfor %}
                        </div>
                        <!-- Divider-->
                        <hr class="my-4" />
                   {% endfor %}
                   <!-- Pager-->

                   {% if is_paginated %}

                   <nav aria-label="Page navigation example text-aline-center" >
                       <ul class="pagination">

                         {% if page_obj.has_previous %}
                           <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}">Previous</a></li>
                         {% endif%}

                         {% for post in page_obj.paginator.page_range %}

                           {% if post.number == page %}
                               <li class="page-item "><a class="page-link" href="?page={{post}}">{{post}}</a></li>
                           {% endif %}

                         {% endfor%}

                         {% if page_obj.has_next %}
                           <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">Next</a></li>
                         {% endif%}

                       </ul>
                   </nav>

                   {% endif %}




                   <!-- {% if post.has_other_pages%}

                   <nav aria-label="Page navigation example text-aline-center" >
                       <ul class="pagination">

                         {% if post.has_previous %}
                           <li class="page-item"><a class="page-link" href="?page={{post.previous_page_number}}">Previous</a></li>
                         {% endif%}

                         {% for post in post.paginator.page_range %}

                           {% if post.number == page %}
                               <li class="page-item "><a class="page-link" href="?page={{post}}">{{post}}</a></li>
                           {% endif %}

                         {% endfor%}

                         {% if post.has_next %}
                           <li class="page-item"><a class="page-link" href="?page={{post.next_page_number}}">Next</a></li>
                         {% endif%}

                       </ul>
                   </nav>

                   {% endif %}
                    -->
                   <!-- <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a></div> -->
                   
                   <!-- End Pager-->
                </div>
            </div>
        </div>
{% endblock %}
      

templates/blog/post.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Post{% endblock %}


{% block header%}
<header class="masthead" style="background-image:url('{{detail.thumbnail.url}}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="post-heading">
                    <h1>{{detail.title}}</h1>
                    <h2 class="subheading">Iranian singer</h2>
                    <span class="meta">
                        Posted by
                        <a href="#!">Start Bootstrap</a>
                        on August 24, 2022
                    </span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}



{% block content %}
<!-- Post Content-->
        <article class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center" >
                    <div class="col-md-10 col-lg-8 col-xl-7 ">
                        
                        <h2 class="section-heading">{{detail.title}}</h2>
                        <p>{{detail.descriptions|linebreaks}}</p>
                        <blockquote class="blockquote">{{detail.publish}}</blockquote>
                        <h2 class="section-heading">Picture</h2>
                        <a href="{{detail.thumbnail.url}}"><img class="img-fluid" src="{{detail.thumbnail.url}}" alt="..." /></a>
                        <span class="caption text-muted">To go places and do things that have never been done before – that’s what living is all about.</span>
                        <p>
                            &middot; {{detail.title}}
                            <a href="http://Wikipedia.com/">Wikipedia</a>
                            <a href="https://www.ostadshajarian.com/">Weblog</a>
                        </p>
                    </div>
                </div>
            </div>
        </article>
     

{% endblock %}

templates/blog/search_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}search{% endblock %}


{% block header%}
<header class="masthead" style="background-image: url('/static/blog/assets/img/se.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>search</h1>
                    <span class="subheading">{{search}} </span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}


{% block content %}
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <h3 class="alert alert-primary text-center">Search {{search}}</h3>
                    <!-- Post preview-->
                    {% for post in object_list %}
                        <div class="post-preview">
                            <a href="{% url 'blog:detail' post.id %}">
                                <h2 class="podfor st-title">{{post.title}}</h2>
                            <img src="{{post.thumbnail.url}}" alt="">
                                <h3 class="post-subtitle">{{post.descriptions |striptags |truncatewords:30}}</h3>
                            </a>
                            <p class="post-meta">
                                Posted by
                                <a href="#!">{{post.author}}</a>
                                {{post.created}}
                            </p>
                            {% for cat in post.category.active %}
                            <a href="{% url 'blog:category' cat.id %}">#{{cat.title}}</a>
                            {% endfor %}
                        </div>
                        <!-- Divider-->
                        <hr class="my-4" />
                   {% empty %}
                        <P>Unfortunately, there is no content to display</P>
                   {% endfor %}
                   <!-- Pager-->

                   {% if is_paginated %}

                   <nav aria-label="Page navigation example text-aline-center" >
                       <ul class="pagination">

                         {% if page_obj.has_previous %}
                           <li class="page-item"><a class="page-link" href="?q={{search}}{{page_obj.previous_page_number}}">Previous</a></li>
                         {% endif%}

                         {% for post in page_obj.paginator.page_range %}

                           {% if post.number == page %}
                               <li class="page-item "><a class="page-link" href="?q={{search}}{{post}}">{{post}}</a></li>
                           {% endif %}

                         {% endfor%}

                         {% if page_obj.has_next %}
                           <li class="page-item"><a class="page-link" href="?q={{search}}{{page_obj.next_page_number}}">Next</a></li>
                         {% endif%}

                       </ul>
                   </nav>

                   {% endif %}




                   <!-- {% if post.has_other_pages%}

                   <nav aria-label="Page navigation example text-aline-center" >
                       <ul class="pagination">

                         {% if post.has_previous %}
                           <li class="page-item"><a class="page-link" href="?page={{post.previous_page_number}}">Previous</a></li>
                         {% endif%}

                         {% for post in post.paginator.page_range %}

                           {% if post.number == page %}
                               <li class="page-item "><a class="page-link" href="?page={{post}}">{{post}}</a></li>
                           {% endif %}

                         {% endfor%}

                         {% if post.has_next %}
                           <li class="page-item"><a class="page-link" href="?page={{post.next_page_number}}">Next</a></li>
                         {% endif%}

                       </ul>
                   </nav>

                   {% endif %}
                    -->
                   <!-- <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a></div> -->
                   
                   <!-- End Pager-->
                </div>
            </div>
        </div>
{% endblock %}
      